name: Dev Container Build and Push Image

on:
  push:
    paths:
    - '.github/.devcontainer/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pre-build Dev Container image
      uses: devcontainers/ci@v0.2
      with:
        subFolder: .github
        imageName: ghcr.io/${{ github.repository }}
        cacheFrom: ghcr.io/${{ github.repository }}
        push: always
