name: LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          # latexmk_use_xelatex: true
      - name: Check output
        run: ls
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: main.pdf
      - name: Check changes
        run: git status
      - name: Exports PDF into the repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add main.pdf
          git commit -m "Adds compiled PDF file"
          git push